name: CI/CD Pipeline

on:
  push:
    branches: [ main, master, development, release ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Display commit info
        run: |
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
          echo "Author: ${{ github.actor }}"
      
      - name: List project files
        run: ls -la
      
      - name: Run unit tests
        run: python -m unittest test_calculator.py -v
      
      - name: Run integration tests
        run: python -m unittest test_integration.py -v
      
      - name: Success message
        run: echo "All tests passed!"
