name: CI/CD Pipeline

on:
  push:
    branches: [ main, master, development, release ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
      
      - name: Display commit info
        run: |
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
          echo "Author: ${{ github.actor }}"
      
      - name: Install dependencies
        run: bundle install
      
      - name: Run tests
        run: bundle exec rspec calculator_spec.rb --format documentation
      
      - name: Success message
        run: echo "All tests passed!"
